// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

/**
 * Protobuf type {@code Action}
 */
public final class Action extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Action)
    ActionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 6,
      /* suffix= */ "",
      Action.class.getName());
  }
  // Use Action.newBuilder() to construct.
  private Action(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Action() {
    group_ = "";
    motion_ = "";
    audio_ = "";
    lipSync_ = "";
    doc_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.desktoppet.bundle.Bundles.internal_static_Action_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.desktoppet.bundle.Bundles.internal_static_Action_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.desktoppet.bundle.Action.class, com.desktoppet.bundle.Action.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int GROUP_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object group_ = "";
  /**
   * <code>string group = 2;</code>
   * @return The group.
   */
  @java.lang.Override
  public java.lang.String getGroup() {
    java.lang.Object ref = group_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      group_ = s;
      return s;
    }
  }
  /**
   * <code>string group = 2;</code>
   * @return The bytes for group.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupBytes() {
    java.lang.Object ref = group_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      group_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MOTION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object motion_ = "";
  /**
   * <code>string motion = 3;</code>
   * @return The motion.
   */
  @java.lang.Override
  public java.lang.String getMotion() {
    java.lang.Object ref = motion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      motion_ = s;
      return s;
    }
  }
  /**
   * <code>string motion = 3;</code>
   * @return The bytes for motion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMotionBytes() {
    java.lang.Object ref = motion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      motion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUDIO_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object audio_ = "";
  /**
   * <code>string audio = 4;</code>
   * @return The audio.
   */
  @java.lang.Override
  public java.lang.String getAudio() {
    java.lang.Object ref = audio_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      audio_ = s;
      return s;
    }
  }
  /**
   * <code>string audio = 4;</code>
   * @return The bytes for audio.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAudioBytes() {
    java.lang.Object ref = audio_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      audio_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LIPSYNC_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lipSync_ = "";
  /**
   * <code>optional string lipSync = 5;</code>
   * @return Whether the lipSync field is set.
   */
  @java.lang.Override
  public boolean hasLipSync() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string lipSync = 5;</code>
   * @return The lipSync.
   */
  @java.lang.Override
  public java.lang.String getLipSync() {
    java.lang.Object ref = lipSync_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lipSync_ = s;
      return s;
    }
  }
  /**
   * <code>optional string lipSync = 5;</code>
   * @return The bytes for lipSync.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLipSyncBytes() {
    java.lang.Object ref = lipSync_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lipSync_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOC_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object doc_ = "";
  /**
   * <code>string doc = 6;</code>
   * @return The doc.
   */
  @java.lang.Override
  public java.lang.String getDoc() {
    java.lang.Object ref = doc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      doc_ = s;
      return s;
    }
  }
  /**
   * <code>string doc = 6;</code>
   * @return The bytes for doc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDocBytes() {
    java.lang.Object ref = doc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      doc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FADEIN_FIELD_NUMBER = 7;
  private long fadeIn_ = 0L;
  /**
   * <code>int64 fadeIn = 7;</code>
   * @return The fadeIn.
   */
  @java.lang.Override
  public long getFadeIn() {
    return fadeIn_;
  }

  public static final int FADEOUT_FIELD_NUMBER = 8;
  private long fadeOut_ = 0L;
  /**
   * <code>int64 fadeOut = 8;</code>
   * @return The fadeOut.
   */
  @java.lang.Override
  public long getFadeOut() {
    return fadeOut_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(group_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, group_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(motion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, motion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(audio_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, audio_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, lipSync_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(doc_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, doc_);
    }
    if (fadeIn_ != 0L) {
      output.writeInt64(7, fadeIn_);
    }
    if (fadeOut_ != 0L) {
      output.writeInt64(8, fadeOut_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(group_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, group_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(motion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, motion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(audio_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, audio_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, lipSync_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(doc_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, doc_);
    }
    if (fadeIn_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, fadeIn_);
    }
    if (fadeOut_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, fadeOut_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.desktoppet.bundle.Action)) {
      return super.equals(obj);
    }
    com.desktoppet.bundle.Action other = (com.desktoppet.bundle.Action) obj;

    if (getId()
        != other.getId()) return false;
    if (!getGroup()
        .equals(other.getGroup())) return false;
    if (!getMotion()
        .equals(other.getMotion())) return false;
    if (!getAudio()
        .equals(other.getAudio())) return false;
    if (hasLipSync() != other.hasLipSync()) return false;
    if (hasLipSync()) {
      if (!getLipSync()
          .equals(other.getLipSync())) return false;
    }
    if (!getDoc()
        .equals(other.getDoc())) return false;
    if (getFadeIn()
        != other.getFadeIn()) return false;
    if (getFadeOut()
        != other.getFadeOut()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + GROUP_FIELD_NUMBER;
    hash = (53 * hash) + getGroup().hashCode();
    hash = (37 * hash) + MOTION_FIELD_NUMBER;
    hash = (53 * hash) + getMotion().hashCode();
    hash = (37 * hash) + AUDIO_FIELD_NUMBER;
    hash = (53 * hash) + getAudio().hashCode();
    if (hasLipSync()) {
      hash = (37 * hash) + LIPSYNC_FIELD_NUMBER;
      hash = (53 * hash) + getLipSync().hashCode();
    }
    hash = (37 * hash) + DOC_FIELD_NUMBER;
    hash = (53 * hash) + getDoc().hashCode();
    hash = (37 * hash) + FADEIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFadeIn());
    hash = (37 * hash) + FADEOUT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFadeOut());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.desktoppet.bundle.Action parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.desktoppet.bundle.Action parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.desktoppet.bundle.Action parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.desktoppet.bundle.Action parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.desktoppet.bundle.Action parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.desktoppet.bundle.Action parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.desktoppet.bundle.Action parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.desktoppet.bundle.Action parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.desktoppet.bundle.Action parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.desktoppet.bundle.Action parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.desktoppet.bundle.Action parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.desktoppet.bundle.Action parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.desktoppet.bundle.Action prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Action}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Action)
      com.desktoppet.bundle.ActionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.desktoppet.bundle.Bundles.internal_static_Action_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.desktoppet.bundle.Bundles.internal_static_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.desktoppet.bundle.Action.class, com.desktoppet.bundle.Action.Builder.class);
    }

    // Construct using com.desktoppet.bundle.Action.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      group_ = "";
      motion_ = "";
      audio_ = "";
      lipSync_ = "";
      doc_ = "";
      fadeIn_ = 0L;
      fadeOut_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.desktoppet.bundle.Bundles.internal_static_Action_descriptor;
    }

    @java.lang.Override
    public com.desktoppet.bundle.Action getDefaultInstanceForType() {
      return com.desktoppet.bundle.Action.getDefaultInstance();
    }

    @java.lang.Override
    public com.desktoppet.bundle.Action build() {
      com.desktoppet.bundle.Action result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.desktoppet.bundle.Action buildPartial() {
      com.desktoppet.bundle.Action result = new com.desktoppet.bundle.Action(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.desktoppet.bundle.Action result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.group_ = group_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.motion_ = motion_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.audio_ = audio_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.lipSync_ = lipSync_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.doc_ = doc_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.fadeIn_ = fadeIn_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.fadeOut_ = fadeOut_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.desktoppet.bundle.Action) {
        return mergeFrom((com.desktoppet.bundle.Action)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.desktoppet.bundle.Action other) {
      if (other == com.desktoppet.bundle.Action.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getGroup().isEmpty()) {
        group_ = other.group_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getMotion().isEmpty()) {
        motion_ = other.motion_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAudio().isEmpty()) {
        audio_ = other.audio_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasLipSync()) {
        lipSync_ = other.lipSync_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getDoc().isEmpty()) {
        doc_ = other.doc_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getFadeIn() != 0L) {
        setFadeIn(other.getFadeIn());
      }
      if (other.getFadeOut() != 0L) {
        setFadeOut(other.getFadeOut());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              group_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              motion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              audio_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              lipSync_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              doc_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              fadeIn_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              fadeOut_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object group_ = "";
    /**
     * <code>string group = 2;</code>
     * @return The group.
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string group = 2;</code>
     * @return The bytes for group.
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string group = 2;</code>
     * @param value The group to set.
     * @return This builder for chaining.
     */
    public Builder setGroup(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      group_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string group = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroup() {
      group_ = getDefaultInstance().getGroup();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string group = 2;</code>
     * @param value The bytes for group to set.
     * @return This builder for chaining.
     */
    public Builder setGroupBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      group_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object motion_ = "";
    /**
     * <code>string motion = 3;</code>
     * @return The motion.
     */
    public java.lang.String getMotion() {
      java.lang.Object ref = motion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        motion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string motion = 3;</code>
     * @return The bytes for motion.
     */
    public com.google.protobuf.ByteString
        getMotionBytes() {
      java.lang.Object ref = motion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        motion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string motion = 3;</code>
     * @param value The motion to set.
     * @return This builder for chaining.
     */
    public Builder setMotion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      motion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string motion = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMotion() {
      motion_ = getDefaultInstance().getMotion();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string motion = 3;</code>
     * @param value The bytes for motion to set.
     * @return This builder for chaining.
     */
    public Builder setMotionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      motion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object audio_ = "";
    /**
     * <code>string audio = 4;</code>
     * @return The audio.
     */
    public java.lang.String getAudio() {
      java.lang.Object ref = audio_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        audio_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string audio = 4;</code>
     * @return The bytes for audio.
     */
    public com.google.protobuf.ByteString
        getAudioBytes() {
      java.lang.Object ref = audio_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        audio_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string audio = 4;</code>
     * @param value The audio to set.
     * @return This builder for chaining.
     */
    public Builder setAudio(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      audio_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string audio = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAudio() {
      audio_ = getDefaultInstance().getAudio();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string audio = 4;</code>
     * @param value The bytes for audio to set.
     * @return This builder for chaining.
     */
    public Builder setAudioBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      audio_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object lipSync_ = "";
    /**
     * <code>optional string lipSync = 5;</code>
     * @return Whether the lipSync field is set.
     */
    public boolean hasLipSync() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string lipSync = 5;</code>
     * @return The lipSync.
     */
    public java.lang.String getLipSync() {
      java.lang.Object ref = lipSync_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lipSync_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string lipSync = 5;</code>
     * @return The bytes for lipSync.
     */
    public com.google.protobuf.ByteString
        getLipSyncBytes() {
      java.lang.Object ref = lipSync_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lipSync_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string lipSync = 5;</code>
     * @param value The lipSync to set.
     * @return This builder for chaining.
     */
    public Builder setLipSync(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lipSync_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional string lipSync = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLipSync() {
      lipSync_ = getDefaultInstance().getLipSync();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>optional string lipSync = 5;</code>
     * @param value The bytes for lipSync to set.
     * @return This builder for chaining.
     */
    public Builder setLipSyncBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lipSync_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object doc_ = "";
    /**
     * <code>string doc = 6;</code>
     * @return The doc.
     */
    public java.lang.String getDoc() {
      java.lang.Object ref = doc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        doc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string doc = 6;</code>
     * @return The bytes for doc.
     */
    public com.google.protobuf.ByteString
        getDocBytes() {
      java.lang.Object ref = doc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        doc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string doc = 6;</code>
     * @param value The doc to set.
     * @return This builder for chaining.
     */
    public Builder setDoc(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      doc_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string doc = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDoc() {
      doc_ = getDefaultInstance().getDoc();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string doc = 6;</code>
     * @param value The bytes for doc to set.
     * @return This builder for chaining.
     */
    public Builder setDocBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      doc_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private long fadeIn_ ;
    /**
     * <code>int64 fadeIn = 7;</code>
     * @return The fadeIn.
     */
    @java.lang.Override
    public long getFadeIn() {
      return fadeIn_;
    }
    /**
     * <code>int64 fadeIn = 7;</code>
     * @param value The fadeIn to set.
     * @return This builder for chaining.
     */
    public Builder setFadeIn(long value) {

      fadeIn_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 fadeIn = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFadeIn() {
      bitField0_ = (bitField0_ & ~0x00000040);
      fadeIn_ = 0L;
      onChanged();
      return this;
    }

    private long fadeOut_ ;
    /**
     * <code>int64 fadeOut = 8;</code>
     * @return The fadeOut.
     */
    @java.lang.Override
    public long getFadeOut() {
      return fadeOut_;
    }
    /**
     * <code>int64 fadeOut = 8;</code>
     * @param value The fadeOut to set.
     * @return This builder for chaining.
     */
    public Builder setFadeOut(long value) {

      fadeOut_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int64 fadeOut = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFadeOut() {
      bitField0_ = (bitField0_ & ~0x00000080);
      fadeOut_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Action)
  }

  // @@protoc_insertion_point(class_scope:Action)
  private static final com.desktoppet.bundle.Action DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.desktoppet.bundle.Action();
  }

  public static com.desktoppet.bundle.Action getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Action>
      PARSER = new com.google.protobuf.AbstractParser<Action>() {
    @java.lang.Override
    public Action parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Action> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Action> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.desktoppet.bundle.Action getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

