// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

public interface ActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Action)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string group = 2;</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 2;</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string motion = 3;</code>
   * @return The motion.
   */
  java.lang.String getMotion();
  /**
   * <code>string motion = 3;</code>
   * @return The bytes for motion.
   */
  com.google.protobuf.ByteString
      getMotionBytes();

  /**
   * <code>string audio = 4;</code>
   * @return The audio.
   */
  java.lang.String getAudio();
  /**
   * <code>string audio = 4;</code>
   * @return The bytes for audio.
   */
  com.google.protobuf.ByteString
      getAudioBytes();

  /**
   * <code>optional string lipSync = 5;</code>
   * @return Whether the lipSync field is set.
   */
  boolean hasLipSync();
  /**
   * <code>optional string lipSync = 5;</code>
   * @return The lipSync.
   */
  java.lang.String getLipSync();
  /**
   * <code>optional string lipSync = 5;</code>
   * @return The bytes for lipSync.
   */
  com.google.protobuf.ByteString
      getLipSyncBytes();

  /**
   * <code>string doc = 6;</code>
   * @return The doc.
   */
  java.lang.String getDoc();
  /**
   * <code>string doc = 6;</code>
   * @return The bytes for doc.
   */
  com.google.protobuf.ByteString
      getDocBytes();

  /**
   * <code>int64 fadeIn = 7;</code>
   * @return The fadeIn.
   */
  long getFadeIn();

  /**
   * <code>int64 fadeOut = 8;</code>
   * @return The fadeOut.
   */
  long getFadeOut();
}
