// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

public interface AiModuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AiModule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>int32 priority = 2;</code>
   * @return The priority.
   */
  int getPriority();

  /**
   * <code>string file = 3;</code>
   * @return The file.
   */
  java.lang.String getFile();
  /**
   * <code>string file = 3;</code>
   * @return The bytes for file.
   */
  com.google.protobuf.ByteString
      getFileBytes();
}
