// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

/**
 * Protobuf enum {@code BundleType}
 */
public enum BundleType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MODEL = 0;</code>
   */
  MODEL(0),
  /**
   * <code>AI = 1;</code>
   */
  AI(1),
  /**
   * <code>SHOW = 2;</code>
   */
  SHOW(2),
  /**
   * <code>STYLE = 3;</code>
   */
  STYLE(3),
  /**
   * <code>EXP = 4;</code>
   */
  EXP(4),
  /**
   * <code>ENV = 5;</code>
   */
  ENV(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 6,
      /* suffix= */ "",
      BundleType.class.getName());
  }
  /**
   * <code>MODEL = 0;</code>
   */
  public static final int MODEL_VALUE = 0;
  /**
   * <code>AI = 1;</code>
   */
  public static final int AI_VALUE = 1;
  /**
   * <code>SHOW = 2;</code>
   */
  public static final int SHOW_VALUE = 2;
  /**
   * <code>STYLE = 3;</code>
   */
  public static final int STYLE_VALUE = 3;
  /**
   * <code>EXP = 4;</code>
   */
  public static final int EXP_VALUE = 4;
  /**
   * <code>ENV = 5;</code>
   */
  public static final int ENV_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static BundleType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static BundleType forNumber(int value) {
    switch (value) {
      case 0: return MODEL;
      case 1: return AI;
      case 2: return SHOW;
      case 3: return STYLE;
      case 4: return EXP;
      case 5: return ENV;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<BundleType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      BundleType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<BundleType>() {
          public BundleType findValueByNumber(int number) {
            return BundleType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.desktoppet.bundle.Bundles.getDescriptor().getEnumTypes().get(0);
  }

  private static final BundleType[] VALUES = values();

  public static BundleType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private BundleType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:BundleType)
}

