// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

public final class Bundles {
  private Bundles() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 6,
      /* suffix= */ "",
      Bundles.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Meta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Meta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Bundle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Bundle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActionGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ActionGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Action_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Action_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AiModule_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AiModule_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Theme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Theme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Timing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Timing_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Env_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Env_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Exp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Exp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wake_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Wake_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FileEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbundles.proto\"g\n\004Meta\022\014\n\004name\030\001 \001(\t\022\014\n" +
      "\004code\030\002 \001(\t\022\031\n\004type\030\003 \001(\0162\013.BundleType\022\014" +
      "\n\004root\030\004 \001(\t\022\032\n\005files\030\005 \003(\0132\013.FileEntity" +
      "\"\243\001\n\006Bundle\022\023\n\004meta\030\001 \001(\0132\005.Meta\022\026\n\006them" +
      "es\030\002 \003(\0132\006.Theme\022\032\n\007modules\030\003 \003(\0132\t.AiMo" +
      "dule\022\034\n\006groups\030\004 \003(\0132\014.ActionGroup\022\030\n\007ac" +
      "tions\030\005 \003(\0132\007.Action\022\030\n\007timings\030\006 \003(\0132\007." +
      "Timing\";\n\013ActionGroup\022\014\n\004code\030\001 \001(\t\022\020\n\010p" +
      "riority\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\"\222\001\n\006Action\022\n" +
      "\n\002id\030\001 \001(\005\022\r\n\005group\030\002 \001(\t\022\016\n\006motion\030\003 \001(" +
      "\t\022\r\n\005audio\030\004 \001(\t\022\024\n\007lipSync\030\005 \001(\tH\000\210\001\001\022\013" +
      "\n\003doc\030\006 \001(\t\022\016\n\006fadeIn\030\007 \001(\003\022\017\n\007fadeOut\030\010" +
      " \001(\003B\n\n\010_lipSync\"7\n\010AiModule\022\013\n\003key\030\001 \001(" +
      "\t\022\020\n\010priority\030\002 \001(\005\022\014\n\004file\030\003 \001(\t\"a\n\005The" +
      "me\022\014\n\004name\030\001 \001(\t\022\014\n\004code\030\002 \001(\t\022\014\n\004root\030\003" +
      " \001(\t\022\014\n\004file\030\004 \001(\t\022\r\n\005color\030\005 \001(\t\022\021\n\tisD" +
      "efault\030\006 \001(\010\"b\n\006Timing\022\014\n\004time\030\001 \001(\002\022\023\n\003" +
      "env\030\002 \001(\0132\004.EnvH\000\022\023\n\003exp\030\003 \001(\0132\004.ExpH\000\022\025" +
      "\n\004wake\030\004 \001(\0132\005.WakeH\000B\t\n\007content\"2\n\003Env\022" +
      "\r\n\005image\030\001 \001(\t\022\022\n\005video\030\002 \001(\tH\000\210\001\001B\010\n\006_v" +
      "ideo\"7\n\003Exp\022\022\n\nbackground\030\001 \001(\t\022\016\n\006actio" +
      "n\030\002 \001(\t\022\014\n\004idle\030\003 \001(\t\"\027\n\004Wake\022\017\n\007isAwake" +
      "\030\001 \001(\010\"+\n\nFileEntity\022\014\n\004path\030\001 \001(\t\022\017\n\007en" +
      "crypt\030\002 \001(\010*F\n\nBundleType\022\t\n\005MODEL\020\000\022\006\n\002" +
      "AI\020\001\022\010\n\004SHOW\020\002\022\t\n\005STYLE\020\003\022\007\n\003EXP\020\004\022\007\n\003EN" +
      "V\020\005B\031\n\025com.desktoppet.bundleP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Meta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Meta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Meta_descriptor,
        new java.lang.String[] { "Name", "Code", "Type", "Root", "Files", });
    internal_static_Bundle_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Bundle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Bundle_descriptor,
        new java.lang.String[] { "Meta", "Themes", "Modules", "Groups", "Actions", "Timings", });
    internal_static_ActionGroup_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ActionGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ActionGroup_descriptor,
        new java.lang.String[] { "Code", "Priority", "Name", });
    internal_static_Action_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Action_descriptor,
        new java.lang.String[] { "Id", "Group", "Motion", "Audio", "LipSync", "Doc", "FadeIn", "FadeOut", });
    internal_static_AiModule_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AiModule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AiModule_descriptor,
        new java.lang.String[] { "Key", "Priority", "File", });
    internal_static_Theme_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Theme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Theme_descriptor,
        new java.lang.String[] { "Name", "Code", "Root", "File", "Color", "IsDefault", });
    internal_static_Timing_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Timing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Timing_descriptor,
        new java.lang.String[] { "Time", "Env", "Exp", "Wake", "Content", });
    internal_static_Env_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Env_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Env_descriptor,
        new java.lang.String[] { "Image", "Video", });
    internal_static_Exp_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Exp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Exp_descriptor,
        new java.lang.String[] { "Background", "Action", "Idle", });
    internal_static_Wake_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Wake_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Wake_descriptor,
        new java.lang.String[] { "IsAwake", });
    internal_static_FileEntity_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_FileEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FileEntity_descriptor,
        new java.lang.String[] { "Path", "Encrypt", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
