// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

public interface BundleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Bundle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Meta meta = 1;</code>
   * @return Whether the meta field is set.
   */
  boolean hasMeta();
  /**
   * <code>.Meta meta = 1;</code>
   * @return The meta.
   */
  com.desktoppet.bundle.Meta getMeta();
  /**
   * <code>.Meta meta = 1;</code>
   */
  com.desktoppet.bundle.MetaOrBuilder getMetaOrBuilder();

  /**
   * <code>repeated .Theme themes = 2;</code>
   */
  java.util.List<com.desktoppet.bundle.Theme> 
      getThemesList();
  /**
   * <code>repeated .Theme themes = 2;</code>
   */
  com.desktoppet.bundle.Theme getThemes(int index);
  /**
   * <code>repeated .Theme themes = 2;</code>
   */
  int getThemesCount();
  /**
   * <code>repeated .Theme themes = 2;</code>
   */
  java.util.List<? extends com.desktoppet.bundle.ThemeOrBuilder> 
      getThemesOrBuilderList();
  /**
   * <code>repeated .Theme themes = 2;</code>
   */
  com.desktoppet.bundle.ThemeOrBuilder getThemesOrBuilder(
      int index);

  /**
   * <code>repeated .AiModule modules = 3;</code>
   */
  java.util.List<com.desktoppet.bundle.AiModule> 
      getModulesList();
  /**
   * <code>repeated .AiModule modules = 3;</code>
   */
  com.desktoppet.bundle.AiModule getModules(int index);
  /**
   * <code>repeated .AiModule modules = 3;</code>
   */
  int getModulesCount();
  /**
   * <code>repeated .AiModule modules = 3;</code>
   */
  java.util.List<? extends com.desktoppet.bundle.AiModuleOrBuilder> 
      getModulesOrBuilderList();
  /**
   * <code>repeated .AiModule modules = 3;</code>
   */
  com.desktoppet.bundle.AiModuleOrBuilder getModulesOrBuilder(
      int index);

  /**
   * <code>repeated .ActionGroup groups = 4;</code>
   */
  java.util.List<com.desktoppet.bundle.ActionGroup> 
      getGroupsList();
  /**
   * <code>repeated .ActionGroup groups = 4;</code>
   */
  com.desktoppet.bundle.ActionGroup getGroups(int index);
  /**
   * <code>repeated .ActionGroup groups = 4;</code>
   */
  int getGroupsCount();
  /**
   * <code>repeated .ActionGroup groups = 4;</code>
   */
  java.util.List<? extends com.desktoppet.bundle.ActionGroupOrBuilder> 
      getGroupsOrBuilderList();
  /**
   * <code>repeated .ActionGroup groups = 4;</code>
   */
  com.desktoppet.bundle.ActionGroupOrBuilder getGroupsOrBuilder(
      int index);

  /**
   * <code>repeated .Action actions = 5;</code>
   */
  java.util.List<com.desktoppet.bundle.Action> 
      getActionsList();
  /**
   * <code>repeated .Action actions = 5;</code>
   */
  com.desktoppet.bundle.Action getActions(int index);
  /**
   * <code>repeated .Action actions = 5;</code>
   */
  int getActionsCount();
  /**
   * <code>repeated .Action actions = 5;</code>
   */
  java.util.List<? extends com.desktoppet.bundle.ActionOrBuilder> 
      getActionsOrBuilderList();
  /**
   * <code>repeated .Action actions = 5;</code>
   */
  com.desktoppet.bundle.ActionOrBuilder getActionsOrBuilder(
      int index);

  /**
   * <code>repeated .Timing timings = 6;</code>
   */
  java.util.List<com.desktoppet.bundle.Timing> 
      getTimingsList();
  /**
   * <code>repeated .Timing timings = 6;</code>
   */
  com.desktoppet.bundle.Timing getTimings(int index);
  /**
   * <code>repeated .Timing timings = 6;</code>
   */
  int getTimingsCount();
  /**
   * <code>repeated .Timing timings = 6;</code>
   */
  java.util.List<? extends com.desktoppet.bundle.TimingOrBuilder> 
      getTimingsOrBuilderList();
  /**
   * <code>repeated .Timing timings = 6;</code>
   */
  com.desktoppet.bundle.TimingOrBuilder getTimingsOrBuilder(
      int index);
}
