// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

/**
 * Protobuf type {@code Bundle}
 */
public final class Bundle extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Bundle)
    BundleOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 6,
      /* suffix= */ "",
      Bundle.class.getName());
  }
  // Use Bundle.newBuilder() to construct.
  private Bundle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Bundle() {
    themes_ = java.util.Collections.emptyList();
    modules_ = java.util.Collections.emptyList();
    groups_ = java.util.Collections.emptyList();
    actions_ = java.util.Collections.emptyList();
    timings_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.desktoppet.bundle.Bundles.internal_static_Bundle_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.desktoppet.bundle.Bundles.internal_static_Bundle_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.desktoppet.bundle.Bundle.class, com.desktoppet.bundle.Bundle.Builder.class);
  }

  private int bitField0_;
  public static final int META_FIELD_NUMBER = 1;
  private com.desktoppet.bundle.Meta meta_;
  /**
   * <code>.Meta meta = 1;</code>
   * @return Whether the meta field is set.
   */
  @java.lang.Override
  public boolean hasMeta() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Meta meta = 1;</code>
   * @return The meta.
   */
  @java.lang.Override
  public com.desktoppet.bundle.Meta getMeta() {
    return meta_ == null ? com.desktoppet.bundle.Meta.getDefaultInstance() : meta_;
  }
  /**
   * <code>.Meta meta = 1;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.MetaOrBuilder getMetaOrBuilder() {
    return meta_ == null ? com.desktoppet.bundle.Meta.getDefaultInstance() : meta_;
  }

  public static final int THEMES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.desktoppet.bundle.Theme> themes_;
  /**
   * <code>repeated .Theme themes = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.desktoppet.bundle.Theme> getThemesList() {
    return themes_;
  }
  /**
   * <code>repeated .Theme themes = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.desktoppet.bundle.ThemeOrBuilder> 
      getThemesOrBuilderList() {
    return themes_;
  }
  /**
   * <code>repeated .Theme themes = 2;</code>
   */
  @java.lang.Override
  public int getThemesCount() {
    return themes_.size();
  }
  /**
   * <code>repeated .Theme themes = 2;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.Theme getThemes(int index) {
    return themes_.get(index);
  }
  /**
   * <code>repeated .Theme themes = 2;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.ThemeOrBuilder getThemesOrBuilder(
      int index) {
    return themes_.get(index);
  }

  public static final int MODULES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.desktoppet.bundle.AiModule> modules_;
  /**
   * <code>repeated .AiModule modules = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.desktoppet.bundle.AiModule> getModulesList() {
    return modules_;
  }
  /**
   * <code>repeated .AiModule modules = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.desktoppet.bundle.AiModuleOrBuilder> 
      getModulesOrBuilderList() {
    return modules_;
  }
  /**
   * <code>repeated .AiModule modules = 3;</code>
   */
  @java.lang.Override
  public int getModulesCount() {
    return modules_.size();
  }
  /**
   * <code>repeated .AiModule modules = 3;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.AiModule getModules(int index) {
    return modules_.get(index);
  }
  /**
   * <code>repeated .AiModule modules = 3;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.AiModuleOrBuilder getModulesOrBuilder(
      int index) {
    return modules_.get(index);
  }

  public static final int GROUPS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.desktoppet.bundle.ActionGroup> groups_;
  /**
   * <code>repeated .ActionGroup groups = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.desktoppet.bundle.ActionGroup> getGroupsList() {
    return groups_;
  }
  /**
   * <code>repeated .ActionGroup groups = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.desktoppet.bundle.ActionGroupOrBuilder> 
      getGroupsOrBuilderList() {
    return groups_;
  }
  /**
   * <code>repeated .ActionGroup groups = 4;</code>
   */
  @java.lang.Override
  public int getGroupsCount() {
    return groups_.size();
  }
  /**
   * <code>repeated .ActionGroup groups = 4;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.ActionGroup getGroups(int index) {
    return groups_.get(index);
  }
  /**
   * <code>repeated .ActionGroup groups = 4;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.ActionGroupOrBuilder getGroupsOrBuilder(
      int index) {
    return groups_.get(index);
  }

  public static final int ACTIONS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.desktoppet.bundle.Action> actions_;
  /**
   * <code>repeated .Action actions = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.desktoppet.bundle.Action> getActionsList() {
    return actions_;
  }
  /**
   * <code>repeated .Action actions = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.desktoppet.bundle.ActionOrBuilder> 
      getActionsOrBuilderList() {
    return actions_;
  }
  /**
   * <code>repeated .Action actions = 5;</code>
   */
  @java.lang.Override
  public int getActionsCount() {
    return actions_.size();
  }
  /**
   * <code>repeated .Action actions = 5;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.Action getActions(int index) {
    return actions_.get(index);
  }
  /**
   * <code>repeated .Action actions = 5;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.ActionOrBuilder getActionsOrBuilder(
      int index) {
    return actions_.get(index);
  }

  public static final int TIMINGS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<com.desktoppet.bundle.Timing> timings_;
  /**
   * <code>repeated .Timing timings = 6;</code>
   */
  @java.lang.Override
  public java.util.List<com.desktoppet.bundle.Timing> getTimingsList() {
    return timings_;
  }
  /**
   * <code>repeated .Timing timings = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.desktoppet.bundle.TimingOrBuilder> 
      getTimingsOrBuilderList() {
    return timings_;
  }
  /**
   * <code>repeated .Timing timings = 6;</code>
   */
  @java.lang.Override
  public int getTimingsCount() {
    return timings_.size();
  }
  /**
   * <code>repeated .Timing timings = 6;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.Timing getTimings(int index) {
    return timings_.get(index);
  }
  /**
   * <code>repeated .Timing timings = 6;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.TimingOrBuilder getTimingsOrBuilder(
      int index) {
    return timings_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getMeta());
    }
    for (int i = 0; i < themes_.size(); i++) {
      output.writeMessage(2, themes_.get(i));
    }
    for (int i = 0; i < modules_.size(); i++) {
      output.writeMessage(3, modules_.get(i));
    }
    for (int i = 0; i < groups_.size(); i++) {
      output.writeMessage(4, groups_.get(i));
    }
    for (int i = 0; i < actions_.size(); i++) {
      output.writeMessage(5, actions_.get(i));
    }
    for (int i = 0; i < timings_.size(); i++) {
      output.writeMessage(6, timings_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMeta());
    }
    for (int i = 0; i < themes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, themes_.get(i));
    }
    for (int i = 0; i < modules_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, modules_.get(i));
    }
    for (int i = 0; i < groups_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, groups_.get(i));
    }
    for (int i = 0; i < actions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, actions_.get(i));
    }
    for (int i = 0; i < timings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, timings_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.desktoppet.bundle.Bundle)) {
      return super.equals(obj);
    }
    com.desktoppet.bundle.Bundle other = (com.desktoppet.bundle.Bundle) obj;

    if (hasMeta() != other.hasMeta()) return false;
    if (hasMeta()) {
      if (!getMeta()
          .equals(other.getMeta())) return false;
    }
    if (!getThemesList()
        .equals(other.getThemesList())) return false;
    if (!getModulesList()
        .equals(other.getModulesList())) return false;
    if (!getGroupsList()
        .equals(other.getGroupsList())) return false;
    if (!getActionsList()
        .equals(other.getActionsList())) return false;
    if (!getTimingsList()
        .equals(other.getTimingsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMeta()) {
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + getMeta().hashCode();
    }
    if (getThemesCount() > 0) {
      hash = (37 * hash) + THEMES_FIELD_NUMBER;
      hash = (53 * hash) + getThemesList().hashCode();
    }
    if (getModulesCount() > 0) {
      hash = (37 * hash) + MODULES_FIELD_NUMBER;
      hash = (53 * hash) + getModulesList().hashCode();
    }
    if (getGroupsCount() > 0) {
      hash = (37 * hash) + GROUPS_FIELD_NUMBER;
      hash = (53 * hash) + getGroupsList().hashCode();
    }
    if (getActionsCount() > 0) {
      hash = (37 * hash) + ACTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getActionsList().hashCode();
    }
    if (getTimingsCount() > 0) {
      hash = (37 * hash) + TIMINGS_FIELD_NUMBER;
      hash = (53 * hash) + getTimingsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.desktoppet.bundle.Bundle parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.desktoppet.bundle.Bundle parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.desktoppet.bundle.Bundle parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.desktoppet.bundle.Bundle parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.desktoppet.bundle.Bundle parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.desktoppet.bundle.Bundle parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.desktoppet.bundle.Bundle parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.desktoppet.bundle.Bundle parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.desktoppet.bundle.Bundle parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.desktoppet.bundle.Bundle parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.desktoppet.bundle.Bundle parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.desktoppet.bundle.Bundle parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.desktoppet.bundle.Bundle prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Bundle}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Bundle)
      com.desktoppet.bundle.BundleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.desktoppet.bundle.Bundles.internal_static_Bundle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.desktoppet.bundle.Bundles.internal_static_Bundle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.desktoppet.bundle.Bundle.class, com.desktoppet.bundle.Bundle.Builder.class);
    }

    // Construct using com.desktoppet.bundle.Bundle.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getMetaFieldBuilder();
        getThemesFieldBuilder();
        getModulesFieldBuilder();
        getGroupsFieldBuilder();
        getActionsFieldBuilder();
        getTimingsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      meta_ = null;
      if (metaBuilder_ != null) {
        metaBuilder_.dispose();
        metaBuilder_ = null;
      }
      if (themesBuilder_ == null) {
        themes_ = java.util.Collections.emptyList();
      } else {
        themes_ = null;
        themesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (modulesBuilder_ == null) {
        modules_ = java.util.Collections.emptyList();
      } else {
        modules_ = null;
        modulesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (groupsBuilder_ == null) {
        groups_ = java.util.Collections.emptyList();
      } else {
        groups_ = null;
        groupsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (actionsBuilder_ == null) {
        actions_ = java.util.Collections.emptyList();
      } else {
        actions_ = null;
        actionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (timingsBuilder_ == null) {
        timings_ = java.util.Collections.emptyList();
      } else {
        timings_ = null;
        timingsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.desktoppet.bundle.Bundles.internal_static_Bundle_descriptor;
    }

    @java.lang.Override
    public com.desktoppet.bundle.Bundle getDefaultInstanceForType() {
      return com.desktoppet.bundle.Bundle.getDefaultInstance();
    }

    @java.lang.Override
    public com.desktoppet.bundle.Bundle build() {
      com.desktoppet.bundle.Bundle result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.desktoppet.bundle.Bundle buildPartial() {
      com.desktoppet.bundle.Bundle result = new com.desktoppet.bundle.Bundle(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.desktoppet.bundle.Bundle result) {
      if (themesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          themes_ = java.util.Collections.unmodifiableList(themes_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.themes_ = themes_;
      } else {
        result.themes_ = themesBuilder_.build();
      }
      if (modulesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          modules_ = java.util.Collections.unmodifiableList(modules_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.modules_ = modules_;
      } else {
        result.modules_ = modulesBuilder_.build();
      }
      if (groupsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          groups_ = java.util.Collections.unmodifiableList(groups_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.groups_ = groups_;
      } else {
        result.groups_ = groupsBuilder_.build();
      }
      if (actionsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          actions_ = java.util.Collections.unmodifiableList(actions_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.actions_ = actions_;
      } else {
        result.actions_ = actionsBuilder_.build();
      }
      if (timingsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          timings_ = java.util.Collections.unmodifiableList(timings_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.timings_ = timings_;
      } else {
        result.timings_ = timingsBuilder_.build();
      }
    }

    private void buildPartial0(com.desktoppet.bundle.Bundle result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.meta_ = metaBuilder_ == null
            ? meta_
            : metaBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.desktoppet.bundle.Bundle) {
        return mergeFrom((com.desktoppet.bundle.Bundle)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.desktoppet.bundle.Bundle other) {
      if (other == com.desktoppet.bundle.Bundle.getDefaultInstance()) return this;
      if (other.hasMeta()) {
        mergeMeta(other.getMeta());
      }
      if (themesBuilder_ == null) {
        if (!other.themes_.isEmpty()) {
          if (themes_.isEmpty()) {
            themes_ = other.themes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureThemesIsMutable();
            themes_.addAll(other.themes_);
          }
          onChanged();
        }
      } else {
        if (!other.themes_.isEmpty()) {
          if (themesBuilder_.isEmpty()) {
            themesBuilder_.dispose();
            themesBuilder_ = null;
            themes_ = other.themes_;
            bitField0_ = (bitField0_ & ~0x00000002);
            themesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getThemesFieldBuilder() : null;
          } else {
            themesBuilder_.addAllMessages(other.themes_);
          }
        }
      }
      if (modulesBuilder_ == null) {
        if (!other.modules_.isEmpty()) {
          if (modules_.isEmpty()) {
            modules_ = other.modules_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureModulesIsMutable();
            modules_.addAll(other.modules_);
          }
          onChanged();
        }
      } else {
        if (!other.modules_.isEmpty()) {
          if (modulesBuilder_.isEmpty()) {
            modulesBuilder_.dispose();
            modulesBuilder_ = null;
            modules_ = other.modules_;
            bitField0_ = (bitField0_ & ~0x00000004);
            modulesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getModulesFieldBuilder() : null;
          } else {
            modulesBuilder_.addAllMessages(other.modules_);
          }
        }
      }
      if (groupsBuilder_ == null) {
        if (!other.groups_.isEmpty()) {
          if (groups_.isEmpty()) {
            groups_ = other.groups_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureGroupsIsMutable();
            groups_.addAll(other.groups_);
          }
          onChanged();
        }
      } else {
        if (!other.groups_.isEmpty()) {
          if (groupsBuilder_.isEmpty()) {
            groupsBuilder_.dispose();
            groupsBuilder_ = null;
            groups_ = other.groups_;
            bitField0_ = (bitField0_ & ~0x00000008);
            groupsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getGroupsFieldBuilder() : null;
          } else {
            groupsBuilder_.addAllMessages(other.groups_);
          }
        }
      }
      if (actionsBuilder_ == null) {
        if (!other.actions_.isEmpty()) {
          if (actions_.isEmpty()) {
            actions_ = other.actions_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureActionsIsMutable();
            actions_.addAll(other.actions_);
          }
          onChanged();
        }
      } else {
        if (!other.actions_.isEmpty()) {
          if (actionsBuilder_.isEmpty()) {
            actionsBuilder_.dispose();
            actionsBuilder_ = null;
            actions_ = other.actions_;
            bitField0_ = (bitField0_ & ~0x00000010);
            actionsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getActionsFieldBuilder() : null;
          } else {
            actionsBuilder_.addAllMessages(other.actions_);
          }
        }
      }
      if (timingsBuilder_ == null) {
        if (!other.timings_.isEmpty()) {
          if (timings_.isEmpty()) {
            timings_ = other.timings_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureTimingsIsMutable();
            timings_.addAll(other.timings_);
          }
          onChanged();
        }
      } else {
        if (!other.timings_.isEmpty()) {
          if (timingsBuilder_.isEmpty()) {
            timingsBuilder_.dispose();
            timingsBuilder_ = null;
            timings_ = other.timings_;
            bitField0_ = (bitField0_ & ~0x00000020);
            timingsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTimingsFieldBuilder() : null;
          } else {
            timingsBuilder_.addAllMessages(other.timings_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMetaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.desktoppet.bundle.Theme m =
                  input.readMessage(
                      com.desktoppet.bundle.Theme.parser(),
                      extensionRegistry);
              if (themesBuilder_ == null) {
                ensureThemesIsMutable();
                themes_.add(m);
              } else {
                themesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              com.desktoppet.bundle.AiModule m =
                  input.readMessage(
                      com.desktoppet.bundle.AiModule.parser(),
                      extensionRegistry);
              if (modulesBuilder_ == null) {
                ensureModulesIsMutable();
                modules_.add(m);
              } else {
                modulesBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              com.desktoppet.bundle.ActionGroup m =
                  input.readMessage(
                      com.desktoppet.bundle.ActionGroup.parser(),
                      extensionRegistry);
              if (groupsBuilder_ == null) {
                ensureGroupsIsMutable();
                groups_.add(m);
              } else {
                groupsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              com.desktoppet.bundle.Action m =
                  input.readMessage(
                      com.desktoppet.bundle.Action.parser(),
                      extensionRegistry);
              if (actionsBuilder_ == null) {
                ensureActionsIsMutable();
                actions_.add(m);
              } else {
                actionsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              com.desktoppet.bundle.Timing m =
                  input.readMessage(
                      com.desktoppet.bundle.Timing.parser(),
                      extensionRegistry);
              if (timingsBuilder_ == null) {
                ensureTimingsIsMutable();
                timings_.add(m);
              } else {
                timingsBuilder_.addMessage(m);
              }
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.desktoppet.bundle.Meta meta_;
    private com.google.protobuf.SingleFieldBuilder<
        com.desktoppet.bundle.Meta, com.desktoppet.bundle.Meta.Builder, com.desktoppet.bundle.MetaOrBuilder> metaBuilder_;
    /**
     * <code>.Meta meta = 1;</code>
     * @return Whether the meta field is set.
     */
    public boolean hasMeta() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Meta meta = 1;</code>
     * @return The meta.
     */
    public com.desktoppet.bundle.Meta getMeta() {
      if (metaBuilder_ == null) {
        return meta_ == null ? com.desktoppet.bundle.Meta.getDefaultInstance() : meta_;
      } else {
        return metaBuilder_.getMessage();
      }
    }
    /**
     * <code>.Meta meta = 1;</code>
     */
    public Builder setMeta(com.desktoppet.bundle.Meta value) {
      if (metaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        meta_ = value;
      } else {
        metaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Meta meta = 1;</code>
     */
    public Builder setMeta(
        com.desktoppet.bundle.Meta.Builder builderForValue) {
      if (metaBuilder_ == null) {
        meta_ = builderForValue.build();
      } else {
        metaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Meta meta = 1;</code>
     */
    public Builder mergeMeta(com.desktoppet.bundle.Meta value) {
      if (metaBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          meta_ != null &&
          meta_ != com.desktoppet.bundle.Meta.getDefaultInstance()) {
          getMetaBuilder().mergeFrom(value);
        } else {
          meta_ = value;
        }
      } else {
        metaBuilder_.mergeFrom(value);
      }
      if (meta_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Meta meta = 1;</code>
     */
    public Builder clearMeta() {
      bitField0_ = (bitField0_ & ~0x00000001);
      meta_ = null;
      if (metaBuilder_ != null) {
        metaBuilder_.dispose();
        metaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Meta meta = 1;</code>
     */
    public com.desktoppet.bundle.Meta.Builder getMetaBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMetaFieldBuilder().getBuilder();
    }
    /**
     * <code>.Meta meta = 1;</code>
     */
    public com.desktoppet.bundle.MetaOrBuilder getMetaOrBuilder() {
      if (metaBuilder_ != null) {
        return metaBuilder_.getMessageOrBuilder();
      } else {
        return meta_ == null ?
            com.desktoppet.bundle.Meta.getDefaultInstance() : meta_;
      }
    }
    /**
     * <code>.Meta meta = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.desktoppet.bundle.Meta, com.desktoppet.bundle.Meta.Builder, com.desktoppet.bundle.MetaOrBuilder> 
        getMetaFieldBuilder() {
      if (metaBuilder_ == null) {
        metaBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.desktoppet.bundle.Meta, com.desktoppet.bundle.Meta.Builder, com.desktoppet.bundle.MetaOrBuilder>(
                getMeta(),
                getParentForChildren(),
                isClean());
        meta_ = null;
      }
      return metaBuilder_;
    }

    private java.util.List<com.desktoppet.bundle.Theme> themes_ =
      java.util.Collections.emptyList();
    private void ensureThemesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        themes_ = new java.util.ArrayList<com.desktoppet.bundle.Theme>(themes_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.desktoppet.bundle.Theme, com.desktoppet.bundle.Theme.Builder, com.desktoppet.bundle.ThemeOrBuilder> themesBuilder_;

    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public java.util.List<com.desktoppet.bundle.Theme> getThemesList() {
      if (themesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(themes_);
      } else {
        return themesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public int getThemesCount() {
      if (themesBuilder_ == null) {
        return themes_.size();
      } else {
        return themesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public com.desktoppet.bundle.Theme getThemes(int index) {
      if (themesBuilder_ == null) {
        return themes_.get(index);
      } else {
        return themesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public Builder setThemes(
        int index, com.desktoppet.bundle.Theme value) {
      if (themesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureThemesIsMutable();
        themes_.set(index, value);
        onChanged();
      } else {
        themesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public Builder setThemes(
        int index, com.desktoppet.bundle.Theme.Builder builderForValue) {
      if (themesBuilder_ == null) {
        ensureThemesIsMutable();
        themes_.set(index, builderForValue.build());
        onChanged();
      } else {
        themesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public Builder addThemes(com.desktoppet.bundle.Theme value) {
      if (themesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureThemesIsMutable();
        themes_.add(value);
        onChanged();
      } else {
        themesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public Builder addThemes(
        int index, com.desktoppet.bundle.Theme value) {
      if (themesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureThemesIsMutable();
        themes_.add(index, value);
        onChanged();
      } else {
        themesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public Builder addThemes(
        com.desktoppet.bundle.Theme.Builder builderForValue) {
      if (themesBuilder_ == null) {
        ensureThemesIsMutable();
        themes_.add(builderForValue.build());
        onChanged();
      } else {
        themesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public Builder addThemes(
        int index, com.desktoppet.bundle.Theme.Builder builderForValue) {
      if (themesBuilder_ == null) {
        ensureThemesIsMutable();
        themes_.add(index, builderForValue.build());
        onChanged();
      } else {
        themesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public Builder addAllThemes(
        java.lang.Iterable<? extends com.desktoppet.bundle.Theme> values) {
      if (themesBuilder_ == null) {
        ensureThemesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, themes_);
        onChanged();
      } else {
        themesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public Builder clearThemes() {
      if (themesBuilder_ == null) {
        themes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        themesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public Builder removeThemes(int index) {
      if (themesBuilder_ == null) {
        ensureThemesIsMutable();
        themes_.remove(index);
        onChanged();
      } else {
        themesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public com.desktoppet.bundle.Theme.Builder getThemesBuilder(
        int index) {
      return getThemesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public com.desktoppet.bundle.ThemeOrBuilder getThemesOrBuilder(
        int index) {
      if (themesBuilder_ == null) {
        return themes_.get(index);  } else {
        return themesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public java.util.List<? extends com.desktoppet.bundle.ThemeOrBuilder> 
         getThemesOrBuilderList() {
      if (themesBuilder_ != null) {
        return themesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(themes_);
      }
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public com.desktoppet.bundle.Theme.Builder addThemesBuilder() {
      return getThemesFieldBuilder().addBuilder(
          com.desktoppet.bundle.Theme.getDefaultInstance());
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public com.desktoppet.bundle.Theme.Builder addThemesBuilder(
        int index) {
      return getThemesFieldBuilder().addBuilder(
          index, com.desktoppet.bundle.Theme.getDefaultInstance());
    }
    /**
     * <code>repeated .Theme themes = 2;</code>
     */
    public java.util.List<com.desktoppet.bundle.Theme.Builder> 
         getThemesBuilderList() {
      return getThemesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.desktoppet.bundle.Theme, com.desktoppet.bundle.Theme.Builder, com.desktoppet.bundle.ThemeOrBuilder> 
        getThemesFieldBuilder() {
      if (themesBuilder_ == null) {
        themesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.desktoppet.bundle.Theme, com.desktoppet.bundle.Theme.Builder, com.desktoppet.bundle.ThemeOrBuilder>(
                themes_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        themes_ = null;
      }
      return themesBuilder_;
    }

    private java.util.List<com.desktoppet.bundle.AiModule> modules_ =
      java.util.Collections.emptyList();
    private void ensureModulesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        modules_ = new java.util.ArrayList<com.desktoppet.bundle.AiModule>(modules_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.desktoppet.bundle.AiModule, com.desktoppet.bundle.AiModule.Builder, com.desktoppet.bundle.AiModuleOrBuilder> modulesBuilder_;

    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public java.util.List<com.desktoppet.bundle.AiModule> getModulesList() {
      if (modulesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(modules_);
      } else {
        return modulesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public int getModulesCount() {
      if (modulesBuilder_ == null) {
        return modules_.size();
      } else {
        return modulesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public com.desktoppet.bundle.AiModule getModules(int index) {
      if (modulesBuilder_ == null) {
        return modules_.get(index);
      } else {
        return modulesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public Builder setModules(
        int index, com.desktoppet.bundle.AiModule value) {
      if (modulesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModulesIsMutable();
        modules_.set(index, value);
        onChanged();
      } else {
        modulesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public Builder setModules(
        int index, com.desktoppet.bundle.AiModule.Builder builderForValue) {
      if (modulesBuilder_ == null) {
        ensureModulesIsMutable();
        modules_.set(index, builderForValue.build());
        onChanged();
      } else {
        modulesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public Builder addModules(com.desktoppet.bundle.AiModule value) {
      if (modulesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModulesIsMutable();
        modules_.add(value);
        onChanged();
      } else {
        modulesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public Builder addModules(
        int index, com.desktoppet.bundle.AiModule value) {
      if (modulesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModulesIsMutable();
        modules_.add(index, value);
        onChanged();
      } else {
        modulesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public Builder addModules(
        com.desktoppet.bundle.AiModule.Builder builderForValue) {
      if (modulesBuilder_ == null) {
        ensureModulesIsMutable();
        modules_.add(builderForValue.build());
        onChanged();
      } else {
        modulesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public Builder addModules(
        int index, com.desktoppet.bundle.AiModule.Builder builderForValue) {
      if (modulesBuilder_ == null) {
        ensureModulesIsMutable();
        modules_.add(index, builderForValue.build());
        onChanged();
      } else {
        modulesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public Builder addAllModules(
        java.lang.Iterable<? extends com.desktoppet.bundle.AiModule> values) {
      if (modulesBuilder_ == null) {
        ensureModulesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, modules_);
        onChanged();
      } else {
        modulesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public Builder clearModules() {
      if (modulesBuilder_ == null) {
        modules_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        modulesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public Builder removeModules(int index) {
      if (modulesBuilder_ == null) {
        ensureModulesIsMutable();
        modules_.remove(index);
        onChanged();
      } else {
        modulesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public com.desktoppet.bundle.AiModule.Builder getModulesBuilder(
        int index) {
      return getModulesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public com.desktoppet.bundle.AiModuleOrBuilder getModulesOrBuilder(
        int index) {
      if (modulesBuilder_ == null) {
        return modules_.get(index);  } else {
        return modulesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public java.util.List<? extends com.desktoppet.bundle.AiModuleOrBuilder> 
         getModulesOrBuilderList() {
      if (modulesBuilder_ != null) {
        return modulesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(modules_);
      }
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public com.desktoppet.bundle.AiModule.Builder addModulesBuilder() {
      return getModulesFieldBuilder().addBuilder(
          com.desktoppet.bundle.AiModule.getDefaultInstance());
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public com.desktoppet.bundle.AiModule.Builder addModulesBuilder(
        int index) {
      return getModulesFieldBuilder().addBuilder(
          index, com.desktoppet.bundle.AiModule.getDefaultInstance());
    }
    /**
     * <code>repeated .AiModule modules = 3;</code>
     */
    public java.util.List<com.desktoppet.bundle.AiModule.Builder> 
         getModulesBuilderList() {
      return getModulesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.desktoppet.bundle.AiModule, com.desktoppet.bundle.AiModule.Builder, com.desktoppet.bundle.AiModuleOrBuilder> 
        getModulesFieldBuilder() {
      if (modulesBuilder_ == null) {
        modulesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.desktoppet.bundle.AiModule, com.desktoppet.bundle.AiModule.Builder, com.desktoppet.bundle.AiModuleOrBuilder>(
                modules_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        modules_ = null;
      }
      return modulesBuilder_;
    }

    private java.util.List<com.desktoppet.bundle.ActionGroup> groups_ =
      java.util.Collections.emptyList();
    private void ensureGroupsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        groups_ = new java.util.ArrayList<com.desktoppet.bundle.ActionGroup>(groups_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.desktoppet.bundle.ActionGroup, com.desktoppet.bundle.ActionGroup.Builder, com.desktoppet.bundle.ActionGroupOrBuilder> groupsBuilder_;

    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public java.util.List<com.desktoppet.bundle.ActionGroup> getGroupsList() {
      if (groupsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(groups_);
      } else {
        return groupsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public int getGroupsCount() {
      if (groupsBuilder_ == null) {
        return groups_.size();
      } else {
        return groupsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public com.desktoppet.bundle.ActionGroup getGroups(int index) {
      if (groupsBuilder_ == null) {
        return groups_.get(index);
      } else {
        return groupsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public Builder setGroups(
        int index, com.desktoppet.bundle.ActionGroup value) {
      if (groupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupsIsMutable();
        groups_.set(index, value);
        onChanged();
      } else {
        groupsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public Builder setGroups(
        int index, com.desktoppet.bundle.ActionGroup.Builder builderForValue) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.set(index, builderForValue.build());
        onChanged();
      } else {
        groupsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public Builder addGroups(com.desktoppet.bundle.ActionGroup value) {
      if (groupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupsIsMutable();
        groups_.add(value);
        onChanged();
      } else {
        groupsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public Builder addGroups(
        int index, com.desktoppet.bundle.ActionGroup value) {
      if (groupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupsIsMutable();
        groups_.add(index, value);
        onChanged();
      } else {
        groupsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public Builder addGroups(
        com.desktoppet.bundle.ActionGroup.Builder builderForValue) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.add(builderForValue.build());
        onChanged();
      } else {
        groupsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public Builder addGroups(
        int index, com.desktoppet.bundle.ActionGroup.Builder builderForValue) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.add(index, builderForValue.build());
        onChanged();
      } else {
        groupsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public Builder addAllGroups(
        java.lang.Iterable<? extends com.desktoppet.bundle.ActionGroup> values) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groups_);
        onChanged();
      } else {
        groupsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public Builder clearGroups() {
      if (groupsBuilder_ == null) {
        groups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        groupsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public Builder removeGroups(int index) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.remove(index);
        onChanged();
      } else {
        groupsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public com.desktoppet.bundle.ActionGroup.Builder getGroupsBuilder(
        int index) {
      return getGroupsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public com.desktoppet.bundle.ActionGroupOrBuilder getGroupsOrBuilder(
        int index) {
      if (groupsBuilder_ == null) {
        return groups_.get(index);  } else {
        return groupsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public java.util.List<? extends com.desktoppet.bundle.ActionGroupOrBuilder> 
         getGroupsOrBuilderList() {
      if (groupsBuilder_ != null) {
        return groupsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(groups_);
      }
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public com.desktoppet.bundle.ActionGroup.Builder addGroupsBuilder() {
      return getGroupsFieldBuilder().addBuilder(
          com.desktoppet.bundle.ActionGroup.getDefaultInstance());
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public com.desktoppet.bundle.ActionGroup.Builder addGroupsBuilder(
        int index) {
      return getGroupsFieldBuilder().addBuilder(
          index, com.desktoppet.bundle.ActionGroup.getDefaultInstance());
    }
    /**
     * <code>repeated .ActionGroup groups = 4;</code>
     */
    public java.util.List<com.desktoppet.bundle.ActionGroup.Builder> 
         getGroupsBuilderList() {
      return getGroupsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.desktoppet.bundle.ActionGroup, com.desktoppet.bundle.ActionGroup.Builder, com.desktoppet.bundle.ActionGroupOrBuilder> 
        getGroupsFieldBuilder() {
      if (groupsBuilder_ == null) {
        groupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.desktoppet.bundle.ActionGroup, com.desktoppet.bundle.ActionGroup.Builder, com.desktoppet.bundle.ActionGroupOrBuilder>(
                groups_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        groups_ = null;
      }
      return groupsBuilder_;
    }

    private java.util.List<com.desktoppet.bundle.Action> actions_ =
      java.util.Collections.emptyList();
    private void ensureActionsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        actions_ = new java.util.ArrayList<com.desktoppet.bundle.Action>(actions_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.desktoppet.bundle.Action, com.desktoppet.bundle.Action.Builder, com.desktoppet.bundle.ActionOrBuilder> actionsBuilder_;

    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public java.util.List<com.desktoppet.bundle.Action> getActionsList() {
      if (actionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(actions_);
      } else {
        return actionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public int getActionsCount() {
      if (actionsBuilder_ == null) {
        return actions_.size();
      } else {
        return actionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public com.desktoppet.bundle.Action getActions(int index) {
      if (actionsBuilder_ == null) {
        return actions_.get(index);
      } else {
        return actionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public Builder setActions(
        int index, com.desktoppet.bundle.Action value) {
      if (actionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActionsIsMutable();
        actions_.set(index, value);
        onChanged();
      } else {
        actionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public Builder setActions(
        int index, com.desktoppet.bundle.Action.Builder builderForValue) {
      if (actionsBuilder_ == null) {
        ensureActionsIsMutable();
        actions_.set(index, builderForValue.build());
        onChanged();
      } else {
        actionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public Builder addActions(com.desktoppet.bundle.Action value) {
      if (actionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActionsIsMutable();
        actions_.add(value);
        onChanged();
      } else {
        actionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public Builder addActions(
        int index, com.desktoppet.bundle.Action value) {
      if (actionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActionsIsMutable();
        actions_.add(index, value);
        onChanged();
      } else {
        actionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public Builder addActions(
        com.desktoppet.bundle.Action.Builder builderForValue) {
      if (actionsBuilder_ == null) {
        ensureActionsIsMutable();
        actions_.add(builderForValue.build());
        onChanged();
      } else {
        actionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public Builder addActions(
        int index, com.desktoppet.bundle.Action.Builder builderForValue) {
      if (actionsBuilder_ == null) {
        ensureActionsIsMutable();
        actions_.add(index, builderForValue.build());
        onChanged();
      } else {
        actionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public Builder addAllActions(
        java.lang.Iterable<? extends com.desktoppet.bundle.Action> values) {
      if (actionsBuilder_ == null) {
        ensureActionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, actions_);
        onChanged();
      } else {
        actionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public Builder clearActions() {
      if (actionsBuilder_ == null) {
        actions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        actionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public Builder removeActions(int index) {
      if (actionsBuilder_ == null) {
        ensureActionsIsMutable();
        actions_.remove(index);
        onChanged();
      } else {
        actionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public com.desktoppet.bundle.Action.Builder getActionsBuilder(
        int index) {
      return getActionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public com.desktoppet.bundle.ActionOrBuilder getActionsOrBuilder(
        int index) {
      if (actionsBuilder_ == null) {
        return actions_.get(index);  } else {
        return actionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public java.util.List<? extends com.desktoppet.bundle.ActionOrBuilder> 
         getActionsOrBuilderList() {
      if (actionsBuilder_ != null) {
        return actionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(actions_);
      }
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public com.desktoppet.bundle.Action.Builder addActionsBuilder() {
      return getActionsFieldBuilder().addBuilder(
          com.desktoppet.bundle.Action.getDefaultInstance());
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public com.desktoppet.bundle.Action.Builder addActionsBuilder(
        int index) {
      return getActionsFieldBuilder().addBuilder(
          index, com.desktoppet.bundle.Action.getDefaultInstance());
    }
    /**
     * <code>repeated .Action actions = 5;</code>
     */
    public java.util.List<com.desktoppet.bundle.Action.Builder> 
         getActionsBuilderList() {
      return getActionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.desktoppet.bundle.Action, com.desktoppet.bundle.Action.Builder, com.desktoppet.bundle.ActionOrBuilder> 
        getActionsFieldBuilder() {
      if (actionsBuilder_ == null) {
        actionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.desktoppet.bundle.Action, com.desktoppet.bundle.Action.Builder, com.desktoppet.bundle.ActionOrBuilder>(
                actions_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        actions_ = null;
      }
      return actionsBuilder_;
    }

    private java.util.List<com.desktoppet.bundle.Timing> timings_ =
      java.util.Collections.emptyList();
    private void ensureTimingsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        timings_ = new java.util.ArrayList<com.desktoppet.bundle.Timing>(timings_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.desktoppet.bundle.Timing, com.desktoppet.bundle.Timing.Builder, com.desktoppet.bundle.TimingOrBuilder> timingsBuilder_;

    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public java.util.List<com.desktoppet.bundle.Timing> getTimingsList() {
      if (timingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(timings_);
      } else {
        return timingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public int getTimingsCount() {
      if (timingsBuilder_ == null) {
        return timings_.size();
      } else {
        return timingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public com.desktoppet.bundle.Timing getTimings(int index) {
      if (timingsBuilder_ == null) {
        return timings_.get(index);
      } else {
        return timingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public Builder setTimings(
        int index, com.desktoppet.bundle.Timing value) {
      if (timingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimingsIsMutable();
        timings_.set(index, value);
        onChanged();
      } else {
        timingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public Builder setTimings(
        int index, com.desktoppet.bundle.Timing.Builder builderForValue) {
      if (timingsBuilder_ == null) {
        ensureTimingsIsMutable();
        timings_.set(index, builderForValue.build());
        onChanged();
      } else {
        timingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public Builder addTimings(com.desktoppet.bundle.Timing value) {
      if (timingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimingsIsMutable();
        timings_.add(value);
        onChanged();
      } else {
        timingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public Builder addTimings(
        int index, com.desktoppet.bundle.Timing value) {
      if (timingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimingsIsMutable();
        timings_.add(index, value);
        onChanged();
      } else {
        timingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public Builder addTimings(
        com.desktoppet.bundle.Timing.Builder builderForValue) {
      if (timingsBuilder_ == null) {
        ensureTimingsIsMutable();
        timings_.add(builderForValue.build());
        onChanged();
      } else {
        timingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public Builder addTimings(
        int index, com.desktoppet.bundle.Timing.Builder builderForValue) {
      if (timingsBuilder_ == null) {
        ensureTimingsIsMutable();
        timings_.add(index, builderForValue.build());
        onChanged();
      } else {
        timingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public Builder addAllTimings(
        java.lang.Iterable<? extends com.desktoppet.bundle.Timing> values) {
      if (timingsBuilder_ == null) {
        ensureTimingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, timings_);
        onChanged();
      } else {
        timingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public Builder clearTimings() {
      if (timingsBuilder_ == null) {
        timings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        timingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public Builder removeTimings(int index) {
      if (timingsBuilder_ == null) {
        ensureTimingsIsMutable();
        timings_.remove(index);
        onChanged();
      } else {
        timingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public com.desktoppet.bundle.Timing.Builder getTimingsBuilder(
        int index) {
      return getTimingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public com.desktoppet.bundle.TimingOrBuilder getTimingsOrBuilder(
        int index) {
      if (timingsBuilder_ == null) {
        return timings_.get(index);  } else {
        return timingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public java.util.List<? extends com.desktoppet.bundle.TimingOrBuilder> 
         getTimingsOrBuilderList() {
      if (timingsBuilder_ != null) {
        return timingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(timings_);
      }
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public com.desktoppet.bundle.Timing.Builder addTimingsBuilder() {
      return getTimingsFieldBuilder().addBuilder(
          com.desktoppet.bundle.Timing.getDefaultInstance());
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public com.desktoppet.bundle.Timing.Builder addTimingsBuilder(
        int index) {
      return getTimingsFieldBuilder().addBuilder(
          index, com.desktoppet.bundle.Timing.getDefaultInstance());
    }
    /**
     * <code>repeated .Timing timings = 6;</code>
     */
    public java.util.List<com.desktoppet.bundle.Timing.Builder> 
         getTimingsBuilderList() {
      return getTimingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.desktoppet.bundle.Timing, com.desktoppet.bundle.Timing.Builder, com.desktoppet.bundle.TimingOrBuilder> 
        getTimingsFieldBuilder() {
      if (timingsBuilder_ == null) {
        timingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.desktoppet.bundle.Timing, com.desktoppet.bundle.Timing.Builder, com.desktoppet.bundle.TimingOrBuilder>(
                timings_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        timings_ = null;
      }
      return timingsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Bundle)
  }

  // @@protoc_insertion_point(class_scope:Bundle)
  private static final com.desktoppet.bundle.Bundle DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.desktoppet.bundle.Bundle();
  }

  public static com.desktoppet.bundle.Bundle getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Bundle>
      PARSER = new com.google.protobuf.AbstractParser<Bundle>() {
    @java.lang.Override
    public Bundle parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Bundle> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Bundle> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.desktoppet.bundle.Bundle getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

