// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

public interface EnvOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Env)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string image = 1;</code>
   * @return The image.
   */
  java.lang.String getImage();
  /**
   * <code>string image = 1;</code>
   * @return The bytes for image.
   */
  com.google.protobuf.ByteString
      getImageBytes();

  /**
   * <code>optional string video = 2;</code>
   * @return Whether the video field is set.
   */
  boolean hasVideo();
  /**
   * <code>optional string video = 2;</code>
   * @return The video.
   */
  java.lang.String getVideo();
  /**
   * <code>optional string video = 2;</code>
   * @return The bytes for video.
   */
  com.google.protobuf.ByteString
      getVideoBytes();
}
