// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

public interface ExpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Exp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string background = 1;</code>
   * @return The background.
   */
  java.lang.String getBackground();
  /**
   * <code>string background = 1;</code>
   * @return The bytes for background.
   */
  com.google.protobuf.ByteString
      getBackgroundBytes();

  /**
   * <code>string action = 2;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <code>string action = 2;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>string idle = 3;</code>
   * @return The idle.
   */
  java.lang.String getIdle();
  /**
   * <code>string idle = 3;</code>
   * @return The bytes for idle.
   */
  com.google.protobuf.ByteString
      getIdleBytes();
}
