// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

public interface MetaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Meta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string code = 2;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>.BundleType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.BundleType type = 3;</code>
   * @return The type.
   */
  com.desktoppet.bundle.BundleType getType();

  /**
   * <code>string root = 4;</code>
   * @return The root.
   */
  java.lang.String getRoot();
  /**
   * <code>string root = 4;</code>
   * @return The bytes for root.
   */
  com.google.protobuf.ByteString
      getRootBytes();

  /**
   * <code>repeated .FileEntity files = 5;</code>
   */
  java.util.List<com.desktoppet.bundle.FileEntity> 
      getFilesList();
  /**
   * <code>repeated .FileEntity files = 5;</code>
   */
  com.desktoppet.bundle.FileEntity getFiles(int index);
  /**
   * <code>repeated .FileEntity files = 5;</code>
   */
  int getFilesCount();
  /**
   * <code>repeated .FileEntity files = 5;</code>
   */
  java.util.List<? extends com.desktoppet.bundle.FileEntityOrBuilder> 
      getFilesOrBuilderList();
  /**
   * <code>repeated .FileEntity files = 5;</code>
   */
  com.desktoppet.bundle.FileEntityOrBuilder getFilesOrBuilder(
      int index);
}
