// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

public interface ThemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Theme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string code = 2;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string root = 3;</code>
   * @return The root.
   */
  java.lang.String getRoot();
  /**
   * <code>string root = 3;</code>
   * @return The bytes for root.
   */
  com.google.protobuf.ByteString
      getRootBytes();

  /**
   * <code>string file = 4;</code>
   * @return The file.
   */
  java.lang.String getFile();
  /**
   * <code>string file = 4;</code>
   * @return The bytes for file.
   */
  com.google.protobuf.ByteString
      getFileBytes();

  /**
   * <code>string color = 5;</code>
   * @return The color.
   */
  java.lang.String getColor();
  /**
   * <code>string color = 5;</code>
   * @return The bytes for color.
   */
  com.google.protobuf.ByteString
      getColorBytes();

  /**
   * <code>bool isDefault = 6;</code>
   * @return The isDefault.
   */
  boolean getIsDefault();
}
