// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

/**
 * Protobuf type {@code Timing}
 */
public final class Timing extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Timing)
    TimingOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 6,
      /* suffix= */ "",
      Timing.class.getName());
  }
  // Use Timing.newBuilder() to construct.
  private Timing(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Timing() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.desktoppet.bundle.Bundles.internal_static_Timing_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.desktoppet.bundle.Bundles.internal_static_Timing_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.desktoppet.bundle.Timing.class, com.desktoppet.bundle.Timing.Builder.class);
  }

  private int contentCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object content_;
  public enum ContentCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ENV(2),
    EXP(3),
    WAKE(4),
    CONTENT_NOT_SET(0);
    private final int value;
    private ContentCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ContentCase valueOf(int value) {
      return forNumber(value);
    }

    public static ContentCase forNumber(int value) {
      switch (value) {
        case 2: return ENV;
        case 3: return EXP;
        case 4: return WAKE;
        case 0: return CONTENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ContentCase
  getContentCase() {
    return ContentCase.forNumber(
        contentCase_);
  }

  public static final int TIME_FIELD_NUMBER = 1;
  private float time_ = 0F;
  /**
   * <code>float time = 1;</code>
   * @return The time.
   */
  @java.lang.Override
  public float getTime() {
    return time_;
  }

  public static final int ENV_FIELD_NUMBER = 2;
  /**
   * <code>.Env env = 2;</code>
   * @return Whether the env field is set.
   */
  @java.lang.Override
  public boolean hasEnv() {
    return contentCase_ == 2;
  }
  /**
   * <code>.Env env = 2;</code>
   * @return The env.
   */
  @java.lang.Override
  public com.desktoppet.bundle.Env getEnv() {
    if (contentCase_ == 2) {
       return (com.desktoppet.bundle.Env) content_;
    }
    return com.desktoppet.bundle.Env.getDefaultInstance();
  }
  /**
   * <code>.Env env = 2;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.EnvOrBuilder getEnvOrBuilder() {
    if (contentCase_ == 2) {
       return (com.desktoppet.bundle.Env) content_;
    }
    return com.desktoppet.bundle.Env.getDefaultInstance();
  }

  public static final int EXP_FIELD_NUMBER = 3;
  /**
   * <code>.Exp exp = 3;</code>
   * @return Whether the exp field is set.
   */
  @java.lang.Override
  public boolean hasExp() {
    return contentCase_ == 3;
  }
  /**
   * <code>.Exp exp = 3;</code>
   * @return The exp.
   */
  @java.lang.Override
  public com.desktoppet.bundle.Exp getExp() {
    if (contentCase_ == 3) {
       return (com.desktoppet.bundle.Exp) content_;
    }
    return com.desktoppet.bundle.Exp.getDefaultInstance();
  }
  /**
   * <code>.Exp exp = 3;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.ExpOrBuilder getExpOrBuilder() {
    if (contentCase_ == 3) {
       return (com.desktoppet.bundle.Exp) content_;
    }
    return com.desktoppet.bundle.Exp.getDefaultInstance();
  }

  public static final int WAKE_FIELD_NUMBER = 4;
  /**
   * <code>.Wake wake = 4;</code>
   * @return Whether the wake field is set.
   */
  @java.lang.Override
  public boolean hasWake() {
    return contentCase_ == 4;
  }
  /**
   * <code>.Wake wake = 4;</code>
   * @return The wake.
   */
  @java.lang.Override
  public com.desktoppet.bundle.Wake getWake() {
    if (contentCase_ == 4) {
       return (com.desktoppet.bundle.Wake) content_;
    }
    return com.desktoppet.bundle.Wake.getDefaultInstance();
  }
  /**
   * <code>.Wake wake = 4;</code>
   */
  @java.lang.Override
  public com.desktoppet.bundle.WakeOrBuilder getWakeOrBuilder() {
    if (contentCase_ == 4) {
       return (com.desktoppet.bundle.Wake) content_;
    }
    return com.desktoppet.bundle.Wake.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Float.floatToRawIntBits(time_) != 0) {
      output.writeFloat(1, time_);
    }
    if (contentCase_ == 2) {
      output.writeMessage(2, (com.desktoppet.bundle.Env) content_);
    }
    if (contentCase_ == 3) {
      output.writeMessage(3, (com.desktoppet.bundle.Exp) content_);
    }
    if (contentCase_ == 4) {
      output.writeMessage(4, (com.desktoppet.bundle.Wake) content_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Float.floatToRawIntBits(time_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, time_);
    }
    if (contentCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.desktoppet.bundle.Env) content_);
    }
    if (contentCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.desktoppet.bundle.Exp) content_);
    }
    if (contentCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.desktoppet.bundle.Wake) content_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.desktoppet.bundle.Timing)) {
      return super.equals(obj);
    }
    com.desktoppet.bundle.Timing other = (com.desktoppet.bundle.Timing) obj;

    if (java.lang.Float.floatToIntBits(getTime())
        != java.lang.Float.floatToIntBits(
            other.getTime())) return false;
    if (!getContentCase().equals(other.getContentCase())) return false;
    switch (contentCase_) {
      case 2:
        if (!getEnv()
            .equals(other.getEnv())) return false;
        break;
      case 3:
        if (!getExp()
            .equals(other.getExp())) return false;
        break;
      case 4:
        if (!getWake()
            .equals(other.getWake())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTime());
    switch (contentCase_) {
      case 2:
        hash = (37 * hash) + ENV_FIELD_NUMBER;
        hash = (53 * hash) + getEnv().hashCode();
        break;
      case 3:
        hash = (37 * hash) + EXP_FIELD_NUMBER;
        hash = (53 * hash) + getExp().hashCode();
        break;
      case 4:
        hash = (37 * hash) + WAKE_FIELD_NUMBER;
        hash = (53 * hash) + getWake().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.desktoppet.bundle.Timing parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.desktoppet.bundle.Timing parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.desktoppet.bundle.Timing parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.desktoppet.bundle.Timing parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.desktoppet.bundle.Timing parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.desktoppet.bundle.Timing parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.desktoppet.bundle.Timing parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.desktoppet.bundle.Timing parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.desktoppet.bundle.Timing parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.desktoppet.bundle.Timing parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.desktoppet.bundle.Timing parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.desktoppet.bundle.Timing parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.desktoppet.bundle.Timing prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Timing}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Timing)
      com.desktoppet.bundle.TimingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.desktoppet.bundle.Bundles.internal_static_Timing_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.desktoppet.bundle.Bundles.internal_static_Timing_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.desktoppet.bundle.Timing.class, com.desktoppet.bundle.Timing.Builder.class);
    }

    // Construct using com.desktoppet.bundle.Timing.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      time_ = 0F;
      if (envBuilder_ != null) {
        envBuilder_.clear();
      }
      if (expBuilder_ != null) {
        expBuilder_.clear();
      }
      if (wakeBuilder_ != null) {
        wakeBuilder_.clear();
      }
      contentCase_ = 0;
      content_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.desktoppet.bundle.Bundles.internal_static_Timing_descriptor;
    }

    @java.lang.Override
    public com.desktoppet.bundle.Timing getDefaultInstanceForType() {
      return com.desktoppet.bundle.Timing.getDefaultInstance();
    }

    @java.lang.Override
    public com.desktoppet.bundle.Timing build() {
      com.desktoppet.bundle.Timing result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.desktoppet.bundle.Timing buildPartial() {
      com.desktoppet.bundle.Timing result = new com.desktoppet.bundle.Timing(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.desktoppet.bundle.Timing result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.time_ = time_;
      }
    }

    private void buildPartialOneofs(com.desktoppet.bundle.Timing result) {
      result.contentCase_ = contentCase_;
      result.content_ = this.content_;
      if (contentCase_ == 2 &&
          envBuilder_ != null) {
        result.content_ = envBuilder_.build();
      }
      if (contentCase_ == 3 &&
          expBuilder_ != null) {
        result.content_ = expBuilder_.build();
      }
      if (contentCase_ == 4 &&
          wakeBuilder_ != null) {
        result.content_ = wakeBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.desktoppet.bundle.Timing) {
        return mergeFrom((com.desktoppet.bundle.Timing)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.desktoppet.bundle.Timing other) {
      if (other == com.desktoppet.bundle.Timing.getDefaultInstance()) return this;
      if (other.getTime() != 0F) {
        setTime(other.getTime());
      }
      switch (other.getContentCase()) {
        case ENV: {
          mergeEnv(other.getEnv());
          break;
        }
        case EXP: {
          mergeExp(other.getExp());
          break;
        }
        case WAKE: {
          mergeWake(other.getWake());
          break;
        }
        case CONTENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              time_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 18: {
              input.readMessage(
                  getEnvFieldBuilder().getBuilder(),
                  extensionRegistry);
              contentCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getExpFieldBuilder().getBuilder(),
                  extensionRegistry);
              contentCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getWakeFieldBuilder().getBuilder(),
                  extensionRegistry);
              contentCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int contentCase_ = 0;
    private java.lang.Object content_;
    public ContentCase
        getContentCase() {
      return ContentCase.forNumber(
          contentCase_);
    }

    public Builder clearContent() {
      contentCase_ = 0;
      content_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private float time_ ;
    /**
     * <code>float time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public float getTime() {
      return time_;
    }
    /**
     * <code>float time = 1;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(float value) {

      time_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>float time = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {
      bitField0_ = (bitField0_ & ~0x00000001);
      time_ = 0F;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.desktoppet.bundle.Env, com.desktoppet.bundle.Env.Builder, com.desktoppet.bundle.EnvOrBuilder> envBuilder_;
    /**
     * <code>.Env env = 2;</code>
     * @return Whether the env field is set.
     */
    @java.lang.Override
    public boolean hasEnv() {
      return contentCase_ == 2;
    }
    /**
     * <code>.Env env = 2;</code>
     * @return The env.
     */
    @java.lang.Override
    public com.desktoppet.bundle.Env getEnv() {
      if (envBuilder_ == null) {
        if (contentCase_ == 2) {
          return (com.desktoppet.bundle.Env) content_;
        }
        return com.desktoppet.bundle.Env.getDefaultInstance();
      } else {
        if (contentCase_ == 2) {
          return envBuilder_.getMessage();
        }
        return com.desktoppet.bundle.Env.getDefaultInstance();
      }
    }
    /**
     * <code>.Env env = 2;</code>
     */
    public Builder setEnv(com.desktoppet.bundle.Env value) {
      if (envBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        envBuilder_.setMessage(value);
      }
      contentCase_ = 2;
      return this;
    }
    /**
     * <code>.Env env = 2;</code>
     */
    public Builder setEnv(
        com.desktoppet.bundle.Env.Builder builderForValue) {
      if (envBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        envBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 2;
      return this;
    }
    /**
     * <code>.Env env = 2;</code>
     */
    public Builder mergeEnv(com.desktoppet.bundle.Env value) {
      if (envBuilder_ == null) {
        if (contentCase_ == 2 &&
            content_ != com.desktoppet.bundle.Env.getDefaultInstance()) {
          content_ = com.desktoppet.bundle.Env.newBuilder((com.desktoppet.bundle.Env) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 2) {
          envBuilder_.mergeFrom(value);
        } else {
          envBuilder_.setMessage(value);
        }
      }
      contentCase_ = 2;
      return this;
    }
    /**
     * <code>.Env env = 2;</code>
     */
    public Builder clearEnv() {
      if (envBuilder_ == null) {
        if (contentCase_ == 2) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 2) {
          contentCase_ = 0;
          content_ = null;
        }
        envBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Env env = 2;</code>
     */
    public com.desktoppet.bundle.Env.Builder getEnvBuilder() {
      return getEnvFieldBuilder().getBuilder();
    }
    /**
     * <code>.Env env = 2;</code>
     */
    @java.lang.Override
    public com.desktoppet.bundle.EnvOrBuilder getEnvOrBuilder() {
      if ((contentCase_ == 2) && (envBuilder_ != null)) {
        return envBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 2) {
          return (com.desktoppet.bundle.Env) content_;
        }
        return com.desktoppet.bundle.Env.getDefaultInstance();
      }
    }
    /**
     * <code>.Env env = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.desktoppet.bundle.Env, com.desktoppet.bundle.Env.Builder, com.desktoppet.bundle.EnvOrBuilder> 
        getEnvFieldBuilder() {
      if (envBuilder_ == null) {
        if (!(contentCase_ == 2)) {
          content_ = com.desktoppet.bundle.Env.getDefaultInstance();
        }
        envBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.desktoppet.bundle.Env, com.desktoppet.bundle.Env.Builder, com.desktoppet.bundle.EnvOrBuilder>(
                (com.desktoppet.bundle.Env) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 2;
      onChanged();
      return envBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.desktoppet.bundle.Exp, com.desktoppet.bundle.Exp.Builder, com.desktoppet.bundle.ExpOrBuilder> expBuilder_;
    /**
     * <code>.Exp exp = 3;</code>
     * @return Whether the exp field is set.
     */
    @java.lang.Override
    public boolean hasExp() {
      return contentCase_ == 3;
    }
    /**
     * <code>.Exp exp = 3;</code>
     * @return The exp.
     */
    @java.lang.Override
    public com.desktoppet.bundle.Exp getExp() {
      if (expBuilder_ == null) {
        if (contentCase_ == 3) {
          return (com.desktoppet.bundle.Exp) content_;
        }
        return com.desktoppet.bundle.Exp.getDefaultInstance();
      } else {
        if (contentCase_ == 3) {
          return expBuilder_.getMessage();
        }
        return com.desktoppet.bundle.Exp.getDefaultInstance();
      }
    }
    /**
     * <code>.Exp exp = 3;</code>
     */
    public Builder setExp(com.desktoppet.bundle.Exp value) {
      if (expBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        expBuilder_.setMessage(value);
      }
      contentCase_ = 3;
      return this;
    }
    /**
     * <code>.Exp exp = 3;</code>
     */
    public Builder setExp(
        com.desktoppet.bundle.Exp.Builder builderForValue) {
      if (expBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        expBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 3;
      return this;
    }
    /**
     * <code>.Exp exp = 3;</code>
     */
    public Builder mergeExp(com.desktoppet.bundle.Exp value) {
      if (expBuilder_ == null) {
        if (contentCase_ == 3 &&
            content_ != com.desktoppet.bundle.Exp.getDefaultInstance()) {
          content_ = com.desktoppet.bundle.Exp.newBuilder((com.desktoppet.bundle.Exp) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 3) {
          expBuilder_.mergeFrom(value);
        } else {
          expBuilder_.setMessage(value);
        }
      }
      contentCase_ = 3;
      return this;
    }
    /**
     * <code>.Exp exp = 3;</code>
     */
    public Builder clearExp() {
      if (expBuilder_ == null) {
        if (contentCase_ == 3) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 3) {
          contentCase_ = 0;
          content_ = null;
        }
        expBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Exp exp = 3;</code>
     */
    public com.desktoppet.bundle.Exp.Builder getExpBuilder() {
      return getExpFieldBuilder().getBuilder();
    }
    /**
     * <code>.Exp exp = 3;</code>
     */
    @java.lang.Override
    public com.desktoppet.bundle.ExpOrBuilder getExpOrBuilder() {
      if ((contentCase_ == 3) && (expBuilder_ != null)) {
        return expBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 3) {
          return (com.desktoppet.bundle.Exp) content_;
        }
        return com.desktoppet.bundle.Exp.getDefaultInstance();
      }
    }
    /**
     * <code>.Exp exp = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.desktoppet.bundle.Exp, com.desktoppet.bundle.Exp.Builder, com.desktoppet.bundle.ExpOrBuilder> 
        getExpFieldBuilder() {
      if (expBuilder_ == null) {
        if (!(contentCase_ == 3)) {
          content_ = com.desktoppet.bundle.Exp.getDefaultInstance();
        }
        expBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.desktoppet.bundle.Exp, com.desktoppet.bundle.Exp.Builder, com.desktoppet.bundle.ExpOrBuilder>(
                (com.desktoppet.bundle.Exp) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 3;
      onChanged();
      return expBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.desktoppet.bundle.Wake, com.desktoppet.bundle.Wake.Builder, com.desktoppet.bundle.WakeOrBuilder> wakeBuilder_;
    /**
     * <code>.Wake wake = 4;</code>
     * @return Whether the wake field is set.
     */
    @java.lang.Override
    public boolean hasWake() {
      return contentCase_ == 4;
    }
    /**
     * <code>.Wake wake = 4;</code>
     * @return The wake.
     */
    @java.lang.Override
    public com.desktoppet.bundle.Wake getWake() {
      if (wakeBuilder_ == null) {
        if (contentCase_ == 4) {
          return (com.desktoppet.bundle.Wake) content_;
        }
        return com.desktoppet.bundle.Wake.getDefaultInstance();
      } else {
        if (contentCase_ == 4) {
          return wakeBuilder_.getMessage();
        }
        return com.desktoppet.bundle.Wake.getDefaultInstance();
      }
    }
    /**
     * <code>.Wake wake = 4;</code>
     */
    public Builder setWake(com.desktoppet.bundle.Wake value) {
      if (wakeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        wakeBuilder_.setMessage(value);
      }
      contentCase_ = 4;
      return this;
    }
    /**
     * <code>.Wake wake = 4;</code>
     */
    public Builder setWake(
        com.desktoppet.bundle.Wake.Builder builderForValue) {
      if (wakeBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        wakeBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 4;
      return this;
    }
    /**
     * <code>.Wake wake = 4;</code>
     */
    public Builder mergeWake(com.desktoppet.bundle.Wake value) {
      if (wakeBuilder_ == null) {
        if (contentCase_ == 4 &&
            content_ != com.desktoppet.bundle.Wake.getDefaultInstance()) {
          content_ = com.desktoppet.bundle.Wake.newBuilder((com.desktoppet.bundle.Wake) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 4) {
          wakeBuilder_.mergeFrom(value);
        } else {
          wakeBuilder_.setMessage(value);
        }
      }
      contentCase_ = 4;
      return this;
    }
    /**
     * <code>.Wake wake = 4;</code>
     */
    public Builder clearWake() {
      if (wakeBuilder_ == null) {
        if (contentCase_ == 4) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 4) {
          contentCase_ = 0;
          content_ = null;
        }
        wakeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Wake wake = 4;</code>
     */
    public com.desktoppet.bundle.Wake.Builder getWakeBuilder() {
      return getWakeFieldBuilder().getBuilder();
    }
    /**
     * <code>.Wake wake = 4;</code>
     */
    @java.lang.Override
    public com.desktoppet.bundle.WakeOrBuilder getWakeOrBuilder() {
      if ((contentCase_ == 4) && (wakeBuilder_ != null)) {
        return wakeBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 4) {
          return (com.desktoppet.bundle.Wake) content_;
        }
        return com.desktoppet.bundle.Wake.getDefaultInstance();
      }
    }
    /**
     * <code>.Wake wake = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.desktoppet.bundle.Wake, com.desktoppet.bundle.Wake.Builder, com.desktoppet.bundle.WakeOrBuilder> 
        getWakeFieldBuilder() {
      if (wakeBuilder_ == null) {
        if (!(contentCase_ == 4)) {
          content_ = com.desktoppet.bundle.Wake.getDefaultInstance();
        }
        wakeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.desktoppet.bundle.Wake, com.desktoppet.bundle.Wake.Builder, com.desktoppet.bundle.WakeOrBuilder>(
                (com.desktoppet.bundle.Wake) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 4;
      onChanged();
      return wakeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Timing)
  }

  // @@protoc_insertion_point(class_scope:Timing)
  private static final com.desktoppet.bundle.Timing DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.desktoppet.bundle.Timing();
  }

  public static com.desktoppet.bundle.Timing getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Timing>
      PARSER = new com.google.protobuf.AbstractParser<Timing>() {
    @java.lang.Override
    public Timing parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Timing> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Timing> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.desktoppet.bundle.Timing getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

