// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

public interface TimingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Timing)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float time = 1;</code>
   * @return The time.
   */
  float getTime();

  /**
   * <code>.Env env = 2;</code>
   * @return Whether the env field is set.
   */
  boolean hasEnv();
  /**
   * <code>.Env env = 2;</code>
   * @return The env.
   */
  com.desktoppet.bundle.Env getEnv();
  /**
   * <code>.Env env = 2;</code>
   */
  com.desktoppet.bundle.EnvOrBuilder getEnvOrBuilder();

  /**
   * <code>.Exp exp = 3;</code>
   * @return Whether the exp field is set.
   */
  boolean hasExp();
  /**
   * <code>.Exp exp = 3;</code>
   * @return The exp.
   */
  com.desktoppet.bundle.Exp getExp();
  /**
   * <code>.Exp exp = 3;</code>
   */
  com.desktoppet.bundle.ExpOrBuilder getExpOrBuilder();

  /**
   * <code>.Wake wake = 4;</code>
   * @return Whether the wake field is set.
   */
  boolean hasWake();
  /**
   * <code>.Wake wake = 4;</code>
   * @return The wake.
   */
  com.desktoppet.bundle.Wake getWake();
  /**
   * <code>.Wake wake = 4;</code>
   */
  com.desktoppet.bundle.WakeOrBuilder getWakeOrBuilder();

  com.desktoppet.bundle.Timing.ContentCase getContentCase();
}
