// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundles.proto
// Protobuf Java Version: 4.29.6

package com.desktoppet.bundle;

public interface WakeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Wake)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isAwake = 1;</code>
   * @return The isAwake.
   */
  boolean getIsAwake();
}
