syntax = "proto3";

option java_package = "com.desktoppet.bundle";
option java_multiple_files = true;

enum BundleType {
  MODEL = 0;
  AI = 1;
  SHOW = 2;
  STYLE = 3;
  EXP = 4;
  ENV = 5;
}

message Meta {
  string name = 1;
  string code = 2;
  BundleType type = 3;
  string root = 4;
  repeated FileEntity files = 5;
}

message Bundle {
  Meta meta = 1;
  repeated Theme themes = 2;
  repeated AiModule modules = 3;
  repeated ActionGroup groups = 4;
  repeated Action actions = 5;
  repeated Timing timings = 6;
}

message ActionGroup {
  string code = 1;
  int32 priority = 2;
  string name = 3;
}

message Action {
  int32 id = 1;
  string group = 2;
  string motion = 3;
  string audio = 4;
  optional string lipSync = 5;
  string doc = 6;
  int64 fadeIn = 7;
  int64 fadeOut = 8;
}

message AiModule {
  string key = 1;
  int32 priority = 2;
  string file = 3;
}

message Theme {
  string name = 1;
  string code = 2;
  string root = 3;
  string file = 4;
  string color = 5;
  bool isDefault = 6;
}

message Timing {
  float time = 1;
  oneof content {
    Env env = 2;
    Exp exp = 3;
    Wake wake = 4;
  }
}

message Env {
  string image = 1;
  optional string video = 2;
}

message Exp {
  string background = 1;
  string action = 2;
  string idle = 3;
}

message Wake {
  bool isAwake = 1;
}

message FileEntity {
  string path = 1;
  bool encrypt = 2;
}
